# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170810_1815'),
        ('store_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuser',
            name='shelves',
            field=models.ManyToManyField(to='books.Shelf'),
        ),
    ]
