# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_users', '0003_auto_20170810_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='identifikator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=50, verbose_name='Название карты')),
                ('card_id', models.CharField(blank=True, max_length=8, verbose_name='id банковской карты')),
            ],
            options={
                'verbose_name': 'Индентификатор',
                'verbose_name_plural': 'Индентификаторы',
            },
        ),
        migrations.AlterModelOptions(
            name='stuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='stuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='stuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='stuser',
            name='shelves',
        ),
        migrations.AddField(
            model_name='stuser',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuser',
            name='bought_books',
            field=models.ManyToManyField(blank=True, to='books.Book', verbose_name='Купленные книги'),
        ),
    ]
