# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_users', '0004_auto_20170811_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuser',
            name='cards',
            field=models.ManyToManyField(blank=True, to='store_users.identifikator', verbose_name='Кредитные карты'),
        ),
    ]
