# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_users', '0007_stuser_card_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuser',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
