# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 12:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='', verbose_name='Uploaded image of author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank='True', max_length=2500)),
                ('photo', models.ImageField(upload_to='', verbose_name='Uploaded image of book')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('authors', models.ManyToManyField(blank='True', to='books.Author')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +79161234567', regex='^\\+\\d{11}$')], verbose_name='Телефон')),
                ('bought_books', models.ManyToManyField(blank='True', to='books.Book')),
            ],
        ),
    ]
