# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('books', models.ManyToManyField(blank='True', to='books.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='bought_books',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
