# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170810_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Uploaded image of book'),
        ),
    ]
