# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170811_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('id',), 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
