# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170811_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('id',), 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='download',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на скачивание книги'),
        ),
    ]
