# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20170811_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='books',
        ),
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
